# Generated by Django 4.0 on 2023-10-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_alter_campaign_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
    ]
