# Generated by Django 4.0 on 2023-11-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
